web:
  build: .
  ports:
    - "3000:3001"
  links:
    - "db"
  working_dir: "/usr/src/app"  
  environment:
    - DB_HOST=db
    - DB_PORT=5432
    - DB_NAME=sinatra
    - DB_USERNAME=sinatra
    - DB_PASSWORD=sinatra
db:
  image: "postgres"
  environment:
    - POSTGRES_USER=sinatra
    - POSTGRES_PASSWORD=sinatra
  ports:
    - "5433:5432"
